services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "${APP_PORT:-80}:80"
    environment:
      - "${APP_PORT:-80}:80"
    command:  pnpm run dev
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
